### ISSUE TITLE
As a developer of go-camel library, I would like to have camel context interface defined.

### ISSUE THREAD

**Issue by vrparmar** [predix/go-camel#1]
- [x] Define project directory structure
- [x] Decide logging, testing library
- [x] Decide dependency manager
- [x] Define camel context interface

**Comment by atulkc** [comment]
logging framework: https://github.com/uber-go/zap
Testing framework: https://github.com/onsi/ginkgo and https://github.com/onsi/gomega
Dependency manager: godep (https://github.com/tools/godep)

**Comment by atulkc** [comment]
https://github.com/predix/go-camel/commit/17487303538ae52ae6ea92fd69629ce03e66297a
